name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.3
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0
  go_router: ^14.6.2
  marquee: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  path_provider: ^2.0.14
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/news/
    - assets/languages/
    - assets/animations/
    - assets/news_tr.json
    - assets/news_en.json
    - assets/default_avatar.png
    - assets/user_avatar.png

